#!/bin/bash

username=$(whiptail --inputbox "Enter a user you want to lock" 8 39 --title "Lock User" 3>&1 1>&2 2>&3)
                                                                        # A trick to swap stdout and stderr.
# Again, you can pack this inside if, but it seems really long for some 80-col terminal users.

exitstatus=$?
if [ $exitstatus = 0 ]; then
sudo id $username &> /dev/null
if [ $? -eq 0 ] 
then
sudo usermod -L $username &> /dev/null
whiptail --title "Done" --msgbox "User $username is locked successfully" 8 78
./main
else
whiptail --title "OOPS" --msgbox "User $username is not existed" 8 78
./main
fi

else
 ./main
fi




