#!/bin/bash

###Check that only root can run this script###
if [ $(id -u) -eq 0 ]
then 


menu=$(whiptail --title "Main Menu" --menu "Choose an option" 25 78 16 \
"Change Password" "Change Password of an existing user" \
"Add Group" "Add a user group to the system" \
"List Groups" "List all groups on the system" \
"Delete Group" "Delete an existing group" \
"Add User" "Add a user to the system" \
"List Users" "List all users on the system" \
"Delete User" "Delete an existing user" \
"Modify User" "Modify an existing user" \
"Enable User" "Unlock the user account" \
"Disable User" "Lock the user account" 3>&1 1>&2 2>&3 )

case $menu in

  "Change Password") ./changepassword ;;
  "Add Group") ./addgroup ;;
  "List Groups") ./listgroups ;;
  "Delete Group") ./deletegroup ;;
  "Add User") ./adduser ;;
  "List Users") ./listusers ;;
  "Delete User") ./deleteuser ;;
  "Modify User") ./modifyuser ;;
  "Enable User") ./enableuser ;;
  "Disable User") ./disableuser ;;

esac




else
whiptail --title "ALERT" --msgbox "Sorry Only Root Can Run This Script :(" 8 78

fi
