#!/bin/bash

###Enter Username you want to modify here####
username=$(whiptail --inputbox "Enter a user you want to Modify" 8 39 --title "Modify User" 3>&1 1>&2 2>&3)

exitstatus=$?
if [ $exitstatus = 0 ];then

###Check if input is empty###
	if [ -z "$username" ]
	then
    		whiptail --title "ERROR" --msgbox "Invalid Input :(" 8 78
        	./main
	fi

###Check existense of username###
	sudo id $username &> /dev/null
	if [ $? -eq 0 ] 
	then

	menu=$(whiptail --title "Modify User" --menu "Choose an option" 25 78 16 \
		"<<BACK" "Back To Main Menu" \
		"Comment" "new value of the GECOS field" \
		"Home Dir" "new home directory for the user account" \
		"UID" "Change UID for the user account" \
		"Expire Date" "set account expiration date to EXPIRE_DATE" \
		"Primary Group" "force use GROUP as new primary group" \
		"Secondary Group" "new list of supplementary groups" \
		"Append Group" "append the user to the supplemental groups" \	
		"Modify GroupID" "append the user to the supplemental groups" \
		"Shell" "new login shell for the user account"  3>&1 1>&2 2>&3)


	case $menu in
     		"<<BACK") ./main ;;
     		"Comment") source ./modifyuser_comment ;;
	     	"Home Dir") source ./modifyuser_homedir ;;
		"UID") source ./modifyuser_uid ;;
      		"Expire Date") source ./modifyuser_expiredate ;;
		"Primary Group") source ./modifyuser_primarygroup ;;
		"Secondary Group") source ./modifyuser_secondarygroup ;;
		"Append Group") source ./modifyuser_appendgroup ;;
		"Modify GroupID") source ./modifyuser_groupid ;;
		"Shell") source ./modifyuser_shell ;;
	esac

	else
	whiptail --title "ERROR" --msgbox "User $username is not existed" 8 78
	./main
	fi



else
 ./main
fi
