#!/bin/bash

yourcomment=$(whiptail --inputbox "Enter your comment" 8 39 --title "User Modify" 3>&1 1>&2 2>&3)

exitstatus=$?
if [ $exitstatus = 0 ]; then
sudo usermod -c "$yourcomment" $username 
whiptail --title "DONE" --msgbox "GECOS field is added successfully" 8 78
 ./main
else
    ./main
fi

