#!/bin/bash

secondarygroup=$(whiptail --inputbox "Enter group name" 8 39 --title "User Modify" 3>&1 1>&2 2>&3)

exitstatus=$?
if [ $exitstatus = 0 ]; then

###Check if input is empty###
        if [ -z "$secondarygroup" ]
        then
            	whiptail --title "OOPS" --msgbox "Invalid Input :(" 8 78
                ./main
        fi

###Check Group Existense###

        sudo getent group $secondarygroup &> /dev/null
        if [ $? = 0 ]; then
        sudo usermod -G "$secondarygroup" $username &> /dev/null 
        whiptail --title "DONE" --msgbox "Group $secondarygroup is set as secondary group to user $username" 8 78
         ./main
        else
	whiptail --title "DONE" --msgbox "Group $secondarygroup is not existed" 8 78
	./main
        fi

else
    ./main
fi


